### ISSUE TITLE
QUESTION: What is the difference between `update_call` and `call_candid_as`?

### ISSUE THREAD

**Issue by saikatdas0790** [dfinity/test-state-machine-client#10]
Both of them let me make calls to a specific canister ID as a specific sender. Is there a difference or are they doing the same thing?

@frederikrothenberger Thoughts?

**Comment by frederikrothenberger** [comment]
Hi @saikatdas0790 

`call_candid_as` uses `update_call` internally and handles the Candid encoding / decoding around the inputs / outputs. `update_call` only handles `Vec<u8>` as input and output.
