### ISSUE TITLE
Request: Add a `state_machine.set_time(time: SystemTime)` method like we have for the older library

### ISSUE THREAD

**Issue by saikatdas0790** [dfinity/test-state-machine-client#13]
Specifically, this:

https://github.com/dfinity/ic/blob/54f4378df245fab9e90dab2b5554678c4756453c/rs/state_machine_tests/src/lib.rs#L841-L847

@frederikrothenberger Thoughts?

**Comment by frederikrothenberger** [comment]
Hi @saikatdas0790 

Could you elaborate why this is required? You can already set a specific time (the initial time is always the same value). The only new capability this would bring is going backwards in time, which is not something the system will ever do...

**Comment by saikatdas0790** [comment]
@frederikrothenberger  It helps us do time based calculations and get deterministic outcomes. We have a test that has test feed scores. Feed scores are calculated based on multiple factors, one of which is how old a post is.

We simulated some tests for it with some hard coded time values and accordingly got some outputs. At this stage it would be much easier to just port those test over as they are instead of going through them and figuring out how to refactor them to use the test start time instead of a fixed point in time.

Does the above make sense?

**Comment by saikatdas0790** [comment]
@frederikrothenberger Any thoughts on the above?

**Comment by frederikrothenberger** [comment]
Yes, that makes sense. I'll see what I can do. I need to change the binary to support this command. And once it is in, I can update the client library.

**Comment by frederikrothenberger** [comment]
@saikatdas0790: Release v2.1.0 adds support to set time and [the binary has been updated as well](https://github.com/dfinity/ic/commit/536d7467cbdb7d67bb1be6ce44731da5cc7d7125).
