### ISSUE TITLE
Feature Request: Mechanism to specify canister cycle balance to simulate low canister balance scenarios

### ISSUE THREAD

**Issue by saikatdas0790** [dfinity/test-state-machine-client#17]
This is primarily to be able to test auto topup mechanisms for canister fleets that we've been working on.

But we imagine it could be used in all other kinds of tests involving cycle balances.

@frederikrothenberger Thoughts?

**Comment by frederikrothenberger** [comment]
Hi @saikatdas0790 

Yeah, so far support for cycles has been sparse because in the II context we don't really need them. It would make sense to expand it.

Do you just need to set the number of cycles to some specific amount or do you need operations to actually burn cycles?

**Comment by saikatdas0790** [comment]
@frederikrothenberger 
Setting is fine for our needs. 

Basically test that low canister balances make the topup functions trigger automatically and perform the requisite actions.

**Comment by frederikrothenberger** [comment]
Hi @saikatdas0790 

Unfortunately, the underlying infrastructure does not allow to easily extend the `test-state-machine` with a way of setting a specific amount of cycles.

However, we could potentially allow setting the subnet configuration such that instructions / messages, storage, etc. actually have a cycles cost other than 0.

With that it should be possible to write a test that exercises the canister under test in such a way (given the cost of operations can be chosen freely) that it falls below certain limits (i.e. to trigger a top-up or fall below the configured freezing threshold).

Would this also satisfy your requirements?

**Comment by frederikrothenberger** [comment]
@saikatdas0790 

Ah, that's a good solution too. In that case I'll close this issue. Thanks for the feedback.

> I think it's a good idea to add this capability in when the underlying infrastructure is refactored in the future and this becomes easier to implement. The reason is, as a integration test harness, it's a good idea for test-state-machine-client to include any behaviour that lets users tweak replica/canister runtime settings programmatically to simulate/test situations that canisters would run into the mainnet.

The testing teams roadmap has a feature for building a much more configurable / tweakable infrastructure similar to the one currently provided. It will definitely be included there. 🙂
