### ISSUE TITLE
REQUEST: Add a mechanism to reinstall a canister

### ISSUE THREAD

**Issue by saikatdas0790** [dfinity/test-state-machine-client#8]
Hi @frederikrothenberger 

I was looking at a way to reinstall a canister and I noticed the available implementations here:
https://github.com/dfinity/test-state-machine-client/blob/45bc3d67a8b0aa45a0bc309cacc5b4e3306b4a9f/src/lib.rs#L167-L199

I was wondering if you would want to add another method called `reinstall_canister` or just create a general `install_canister` method with another additional parameter that takes in a type of `CanisterInstallMode`.

Thoughts?

Happy to send you a PR either way. Let me know

**Comment by frederikrothenberger** [comment]
Hi @saikatdas0790, yes a PR would be nice.

Given that with a `reinstall_canister` function all possible variants of the `InstallCodeArgument` are exhausted anyway, I would go with a PR that introduces the `reinstall_canister` function.

Thanks a lot for your contributions!
